server:
  port: 8081

kavita:
  url: https:<.......>kavita/
  library:
    ids: 1,2,3,4
  token: jwtTokenHere(will be removed shortly when jwt rotation implemented using api key)
  api:
    key: 123456abc


autobrr:
  url: https:<........>/autobrr/