server:
  port: 8081

kavita:
  url: https:<.......>kavita/
  library:
    ids: 1,2,3,4
  apiKey: 123456abc


autobrr:
  url: https:<........>/autobrr/
  basicAuth: true
  username: admin
  password: password
  apiKey: 123546374abc
  filterId: 14

releases:
  releaseGroup:
    name: niceGroup1
    position: after